import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "@/styles/globals.css"

const inter = Merriweather({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "GathSession",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative h-svh overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}
